[package]
name = "micro-pariter"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
criterion = "=0.3.6"
criterion-perf-events = "0.2.0"
perfcnt = "0.8.0"
x86 = "0.47.0"

[[bench]]
name = "bench_pariter"
harness = false

[features]
bench = []

[lib]
bench = false

[[bin]]
name = "micro-pariter"
path = "src/main.rs"
bench = false